### ISSUE TITLE
XMP Toolkit error 201: Error in XMLValidator

### ISSUE THREAD

**Issue by Ares-cz** [LeoHsiao1/pyexiv2#114]
when using macOS with Intel chip to test pyexiv2

> img = pyexiv2.Image('./test_image/MS600_0007_450nm.tif')
> data = img.read_xmp()
> 
> print(data)
> img.close()

while it has an error:

`RuntimeError: XMP Toolkit error 201: Error in XMLValidator`

**Comment by LeoHsiao1** [comment]
This seems to be a resolved issue of exiv2.
https://github.com/Exiv2/exiv2/pull/2133
I would upgrade the version of exiv2 that pyexiv2 depends on to fix the issue.
Alternatively, you can use the method `img.read_raw_xmp()`.

**Comment by Ares-cz** [comment]
> 

I have tried your method, but it doesn't work.

I look forward your upgrade on this issue.

**Comment by Ares-cz** [comment]
`import pyexiv2

img = pyexiv2.Image('./test_image/MS600_0007_450nm.tif')
data = img.read_raw_xmp()
print(data)

img.close()`

> The error shows on the `img = pyexiv2.Image('./test_image/MS600_0007_450nm.tif')`

**Comment by LeoHsiao1** [comment]
I just released [v2.8.2](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.8.2), please try it!
`pip install pyexiv2==2.8.2`

**Comment by Ares-cz** [comment]
![image](https://github.com/LeoHsiao1/pyexiv2/assets/33047738/50305254-728e-4ddb-8107-9f9b0323b3f6)
it still have the same problem.
i am not sure if the problem on my image
because i try another image, it could be worked.

**Comment by LeoHsiao1** [comment]
This is probably because the xmp metadata for this image is not standardized.
Please try exiv2 to see if it can read the xmp metadata for that image.
1. Download exiv2 from https://exiv2.org/download.html
2. execute the command `exiv2 --print x MS600_0007_450nm.tif`
